import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const OUT = fileURLToPath(new URL('../../public/fonts/', import.meta.url));

const FAMILIES = [
  {
    spec: 'Inter:wght@400..700',
    file: 'inter-var',
    family: 'Inter',
    licenceDirectory: 'inter',
    licenceFile: 'inter-OFL.txt',
  },
  // Display. Weight axis only: the width axis costs 54 kB on its own (88 kB
  // vs 34 kB for the latin subset) and the masthead sets normal width anyway.
  {
    spec: 'Archivo:wght@400..900',
    file: 'archivo-var',
    family: 'Archivo',
    licenceDirectory: 'archivo',
    licenceFile: 'archivo-OFL.txt',
  },
  {
    spec: 'Geist+Mono:wght@400..600',
    file: 'geist-mono',
    family: 'Geist Mono',
    licenceDirectory: 'geistmono',
    licenceFile: 'geist-mono-OFL.txt',
  },
];

// Keep only the latin blocks. Everything else is dead weight for an English site.
const KEEP = new Set(['latin', 'latin-ext']);

await mkdir(OUT, { recursive: true });
const out = [];

for (const { spec, file, family, licenceDirectory, licenceFile } of FAMILIES) {
  const licenceResponse = await fetch(
    `https://raw.githubusercontent.com/google/fonts/main/ofl/${licenceDirectory}/OFL.txt`
  );
  if (!licenceResponse.ok) {
    throw new Error(
      `Could not fetch the ${family} licence: ${licenceResponse.status}`
    );
  }
  const licence = await licenceResponse.text();
  if (!licence.includes('SIL OPEN FONT LICENSE Version 1.1')) {
    throw new Error(`Unexpected licence response for ${family}`);
  }
  await writeFile(`${OUT}/${licenceFile}`, licence);

  const css = await fetch(
    `https://fonts.googleapis.com/css2?family=${spec}&display=swap`,
    { headers: { 'User-Agent': UA } }
  ).then((r) => r.text());

  // Blocks are emitted as: /* subset */\n@font-face { ... }
  const blocks = [
    ...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g),
  ];

  for (const [, subset, block] of blocks) {
    if (!KEEP.has(subset)) continue;

    const url = block.match(/url\((https:[^)]+)\)/)[1];
    const style = /font-style:\s*italic/.test(block) ? 'italic' : 'normal';
    const weight = block.match(/font-weight:\s*([^;]+);/)[1].trim();
    // Variable width axis, when the family has one (Archivo).
    const stretch = block.match(/font-stretch:\s*([^;]+);/)?.[1].trim();
    const range = block.match(/unicode-range:\s*([^;]+);/)[1].trim();

    const name = `${file}-${subset}${style === 'italic' ? '-italic' : ''}.woff2`;
    const buf = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
    await writeFile(`${OUT}/${name}`, buf);
    console.log(`${name.padEnd(38)} ${(buf.length / 1024).toFixed(1)} kB`);

    out.push(
      `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        (stretch ? `  font-stretch: ${stretch};\n` : '') +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${name}') format('woff2');\n` +
        `  unicode-range: ${range};\n` +
        `}`
    );
  }
}

await writeFile(
  new URL('../../src/styles/fonts.css', import.meta.url),
  `/* Generated by dev-tools/scripts/fetch-fonts.mjs — do not edit by hand. */\n\n` +
    out.join('\n\n') +
    '\n'
);
console.log(`\n${out.length} @font-face rules written to src/styles/fonts.css`);
